flaskblog/posts/forms.py
# ============== Import Statements ============== #
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

# ============== Post Form Class ============== #
class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
# ============== Import Statements ============== #
from flask import render_template, request, Blueprint
from flaskblog.models import Post

# ============== Blueprint Statement ============== #
main = Blueprint('main', __name__)

# ============== Main/Home Route ============== #
@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')

# ============== About Route ============== #
@main.route("/about")
def about():
    return render_template('about.html', title='About')

# ============== Rankings Route ============== #
@main.route("/rankings")
def rankings():
    return render_template('rankings.html', title='Rankings')

# ============== Forum Route ============== #
@main.route("/forum")
def forum():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('forum.html', title='Forum', posts=posts)

flaskblog/posts/routes.py
# ============== Import Statements ============== #
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

# ============== Blueprint Statement ============== #
posts = Blueprint('posts', __name__)

# ============== New Post Route ============== #
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.forum'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

# ============== Post Route ============== #
@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

# ============== Update Post Route ============== #
@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

# ============== Delete Post Route ============== #
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.forum'))

flaskblog/users/routes.py
# ============== Import Statements ============== #
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_user, logout_user, login_required, login_manager
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email

# ============== Blueprint Statement ============== #
users = Blueprint('users', __name__)

# ============== Register Route ============== #
@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pass)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

# ============== Login Route ============== #
@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

# ============== Logout Route ============== #
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

# ============== Account Route ============== #
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account(): 
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='img/profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form) 

# ============== Users Post Route ============== #
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

# ============== Reset Password Email Route ============== #
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

# ============== Reset Password Route ============== #
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pass
        db.session.commit()
        flash('Your password has been updated! You are now able to login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/forum.html
<!-- Layout Extension -->
{% extends "layout.html" %}

<!-- Block Start -->
{% block content %}
    <div class="content-section">
        <h1>Forum</h1>
        <hr>
        <!-- Post Start -->
        {% for post in posts.items %}
            <article class="media content-post">
                <img class='rounded-circle article-img' src="{{ url_for('static', filename='img/profile_pics/' + post.author.image_file) }}" alt="profile picture">
                <div class="media-body">
                    <!-- Meta-data Start -->
                    <div class="article-metadata">
                        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                    </div>
                    <!-- Meta-data End -->
                    <!-- Post Content Start -->
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.content }}</p>
                    <!-- Post Content End -->
                </div>
            </article>
        {% endfor %}
        <!-- Post End -->
        <!-- Pagination Start -->
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.forum', page=page_num)}}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.forum', page=page_num)}}">{{ page_num }}</a>
                {% endif%}
            {% else %}
                ...
            {% endif%}
        {% endfor %}
        <!-- Pagination End -->
    </div>
{% endblock content %}
<!-- Block End -->

flaskblog/templates/home.html
<!-- Layout Extension -->
{% extends "layout.html" %}

<!-- Block Start -->
{% block content %}
    <div class="content-section">
        <h1 class="home-title">Welcome to the Fantasy Football BlogSpot!</h1>
        <hr>
        <!-- Carousel Start -->
        <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <!-- Slides Start -->
            <div class="carousel-inner">
                <!-- Slide 1 Start -->
                <div class="carousel-item active" data-interval="8000">
                    <a href="{{ url_for('main.forum') }}"><img class="d-block w-100" src="{{ url_for('static', filename='img/pexels-fabricio-trujillo-54567.jpg') }}" alt="field"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <a href="{{ url_for('main.forum') }}"><h5>Under Contstruction</h5></a>
                        <p>The team is hard at work getting things ready to take the field come the 2021 season!</p>
                    </div>
                </div>
                <!-- Slide 1 End -->
                <!-- Slide 2 Start -->
                <div class="carousel-item" data-interval="5000">
                    <a href="{{ url_for('main.forum') }}"><img class="d-block w-100" src="{{ url_for('static', filename='img/pexels-pixabay-209954.jpg') }}" alt="ref"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <a href="{{ url_for('main.forum') }}"><h5>2021 NFL Rule Changes</h5></a>
                        <p>Starting in 2021, the NFL has the option to expand the regular season from 16 to 17 games...</p>
                    </div>
                </div>
                <!-- Slide 2 End -->
                <!-- Slide 3 Start -->
                <div class="carousel-item" data-interval="5000">
                    <a href="{{ url_for('main.rankings') }}"><img class="d-block w-100" src="{{ url_for('static', filename='img/pexels-lucas-andrade-2862718.jpg') }}" alt="helmet"></a>
                    <div class="carousel-caption d-none d-md-block">
                        <a href="{{ url_for('main.rankings') }}"><h5>Early Projections 2021</h5></a>
                        <p>It's never to early to start thinking about next season, 2021 predications coming soon.</p>
                    </div>
                </div>
                <!-- Slide 3 End -->
            </div>
            <!-- Slides End -->
            <!-- Carousel Navigation Start -->
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
                <span class="visually-hidden">Next</span>
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
            <!-- Carousel Navigation End -->
        </div>
        <!-- Carousel End -->
        <hr>
    </div>
    <!-- Sponsorship Start -->
    <div class="content-section">
        <div class="card text-center">
            <!-- Title Start -->
            <div class="card-header">
                Sponsor
            </div>
            <!-- Title End -->
            <!-- Message Start -->
            <div class="card-body">
                <h5 class="card-title">Insert Company Name</h5>
                <p class='text-muted'>Interested in sponsoring the Podcast? Contact us:
                    <a href="mailto:fantasyfootball.blogspot@gmail.com">fantasyfootball.blogspot@gmail.com</a>.
                </p> 
                <a href="#" class="btn btn-primary">Your Product Link</a>
            </div>
            <!-- Message End -->
        </div>
    </div>
    <!-- Sponsorship End -->
{% endblock content %}
<!-- Block End -->

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <!-- Title -->
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
    
</head>
<body>
    <!-- Header Section Start -->
    <header class="site-header">
        <!-- Navigation Start -->
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/"><img src="{{ url_for('static', filename='img/logo-no-bg-2.png') }}" alt="FF-BlogSpot Logo"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Navigation Links Start -->
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <!-- Navbar Left Side -->
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.rankings') }}">Rankings</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.forum') }}">Forum</a>
                    </div>
                    <!-- Navbar Left Side End -->
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side End -->
                </div>
                <!-- Navigation Links End -->
            </div>
        </nav>
        <!-- Navigation End -->
    </header>
    <!-- Header Section End -->
    <!-- Main Section Start-->
    <main role="main" class="container">
        <!-- Content start-->
        <div class="row">
            <!-- Left Column Start -->
            <div class="col-md-8 mt-4">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <!-- Left Column End -->
            <!-- Right Column Start -->
            <div class="col-md-4 mt-4">
                <div class="content-section">
                    <img class="column-logo" src="{{ url_for('static', filename='img/ff-blogspot-podcast-icon-name.png') }}" alt="logo">
                    <hr>
                    <!-- Social Links Start -->
                    <div>
                        <h3>Follow Us</h3>
                        <p class='text-muted'>Want more content, follow us at:
                            <ul class="list-group">
                                <li class="list-group-item list-group-item-light spotify"><a id="Spotify" href="https://www.spotify.com/"><i class="fab fa-spotify"></i>Spotify</a></li>
                                <li class="list-group-item list-group-item-light youtube"><a id="YouTube" href="https://www.youtube.com/"><i class="fab fa-youtube"></i>YouTube</a></li>
                                <li class="list-group-item list-group-item-light twitter"><a id="Twitter" href="https://twitter.com/"><i class="fab fa-twitter"></i>Twitter</a></li>
                                <li class="list-group-item list-group-item-light instagram"><a id="Instagram" href="https://www.instagram.com/"><i class="fab fa-instagram"></i>Instagram</a></li>
                            </ul>
                        </p>
                    </div>
                    <!-- Social Links End -->
                    <hr>
                    <!-- Contact Information Start -->
                    <div>
                        <h3>Contact Us</h3>
                        <address>
                            <h5>FF-BlogSpot, Inc.</h5>
                            <p class="text-muted">
                                12345 Main St, Suite 100
                                <br>
                                Taneytown, MD 21787
                                <br>
                                P: (123) 456-7890
                            </p>
                            <br>
                            <p class='text-muted'>
                                Interested in sponsoring the Podcast? Contact us:
                                <a id="mail-address" href="mailto:fantasyfootball.blogspot@gmail.com">fantasyfootball.blogspot@gmail.com</a>
                                <a id="mail-icon" href="mailto:fantasyfootball.blogspot@gmail.com"><i class="fas fa-envelope fa-2x"></i></a>
                            </p>
                        </address>
                    </div>
                    <!-- Contact Information End -->
                </div>
            </div>
            <!-- Right Column End -->
        </div>
        <!-- Content End-->
    </main>
    <!-- Main Section End-->

    <!-- Footer Section -->
    <footer id="footer">
        <div class="container">
            <!-- Content start-->
            <div class="row d-flex flex-column align-items-center">
                <!-- Logo Start-->
                <div class="footer-logo">
                    <img src="{{ url_for('static', filename='img/logo-no-bg-2.png') }}" alt="logo">
                </div>
                <!-- Logo end-->

                <!-- Social Start-->
                <div class="social-icons">
                    <a href="https://www.spotify.com/"><i class="fab fa-spotify"></i></a>
                    <a href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>
                    <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                    <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                </div>
                <!-- Social end-->

                <!-- Legal start-->
                <div class="copyright">
                    <i class="far fa-copyright"> 2020 </i>
                </div>
                <!-- Legal end-->
            </div>
            <!-- Content end-->
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Optional JavaScript -->
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
<!-- Layout Extension -->
{% extends "layout.html" %}

<!-- Block Start -->
{% block content %}
    <div class="content-section">
        <!-- Form Start -->
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <!-- Email Start -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- Error Start -->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                    <!-- Error End -->
                </div>
                <!-- Email End -->
                <!-- Password Start -->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    <!-- Error Start -->
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                    <!-- Error End -->
                </div>
                <!-- Password End -->
                <!-- Remember Check End -->
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
                <!-- Remember Check End -->
                <!-- Submit Start -->
                <div class="form-group mt-2">
                    {{ form.submit(class="btn btn-info") }}
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>
                <!-- Submit End -->
            </fieldset>
        </form>
        <!-- Form End -->
    </div>

    <!-- New User Start -->
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    <!-- New User End -->
{% endblock content %}
<!-- Block End -->

flaskblog/templates/post.html
<!-- Layout Extension -->
{% extends "layout.html" %}

<!-- Block Start -->
{% block content %}
    <!-- Post Start -->
    <article class="media content-section">
        <img class='rounded-circle article-img' src="{{ url_for('static', filename='img/profile_pics/' + post.author.image_file) }}" alt="profile picture">
        <div class="media-body">
            <!-- Meta-data Start -->
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                <!-- Options Start -->
                {% if post.author == current_user %}
                    <div>
                        <a class='btn btn-secondary btn-sm m-1' href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm mt-1 mb-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif%}
                <!-- Options End -->
            </div>
            <!-- Meta-data End -->
            <!-- Post Content Start -->
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
            <!-- Post Content End -->
        </div>
    </article>
    <!-- Post End -->
    <!-- Modal Start -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <!-- Title Start -->
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <!-- Title End -->
                <!-- Message Start -->
                <div class="modal-body">
                    <p>Are you sure you want to delete this post? Changes cannot be undone!</p>
                </div>
                <!-- Message End -->
                <!-- Options Start -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
                <!-- Options End -->
            </div>
        </div>
    </div>
    <!-- Modal End -->
{% endblock content %}
<!-- Block End -->

flaskblog/templates/user_posts.html
<!-- Layout Extension -->
{% extends "layout.html" %}

<!-- Block Start -->
{% block content %}
    <!-- Users Post Start -->
    <div class="content-section">
        <h1 class="mb-3">Posts by: {{ user.username }} ({{ posts.total }})</h1>
        <!-- Post Start -->
        {% for post in posts.items %}
        <article class="media content-post">
            <img class='rounded-circle article-img' src="{{ url_for('static', filename='img/profile_pics/' + post.author.image_file) }}" alt="profile picture">
            <div class="media-body">
                <!-- Meta-data Start -->
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <!-- Meta-data End -->
                <!-- Post Content Start -->
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                <!-- Post Content End -->
            </div>
        </article>
        {% endfor %}
        <!-- Post End -->
        <!-- Pagination Start -->
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
                {% endif%}
            {% else %}
                ...
            {% endif%}
        {% endfor %}
        <!-- Pagination End -->
    </div>
    <!-- Users Post End -->
{% endblock content %}
<!-- Block End -->